chore: setting firebase environments
next-web-technology/symbol-social-wallet pull request #40
Opened 2023-03-05 15:24 UTC by kobakaku

close #39

2023-03-05 16:05 UTC, kobakaku commented
Please try to merge this branch !!
I will check if Github Actions work correctly .

2023-03-21 07:03 UTC, kobakaku commented
You can see that e2e test works !

Please try merging this branch to main and check cd-firebase-testnet.yml !!

2023-03-22 00:50 UTC, YasunoriMATSUOKA commented
@kobakaku 

I guess CI Web Angular E2E fails on https://github.com/next-web-technology/symbol-social-wallet/tree/feature/setting-firebase-environments

ex. https://github.com/next-web-technology/symbol-social-wallet/actions/runs/4485195103

Can you fix that?

It seems to be not counted as checks because it is deployment or invalid yml file.

2023-03-22 01:07 UTC, YasunoriMATSUOKA requested changes
- Fix GitHub Actions yml files and check them to pass.
- Add only keys related firebase config. (Do not add real values related firebase config. Value should be dummy. (ex. `""`))

2023-03-22 01:07 UTC, YasunoriMATSUOKA commented on projects/web/src/environments/environment.example.ts
> +  // Put the information of firebaseConfig to GitHub
We need to add only key into example env file.
But do not add real value of firebase config values.

2023-03-24 08:30 UTC, YasunoriMATSUOKA requested changes
Check review comments.

2023-03-24 08:30 UTC, YasunoriMATSUOKA commented on .github/workflows/ci-web-angular-build.yml
> +      name: testnet
With this, testnet environment secret is used.
I guess you need to remove this to change this github actions from deployment to check.

2023-03-24 08:30 UTC, YasunoriMATSUOKA commented on .github/workflows/ci-web-angular-e2e.yml
> +      name: testnet
With this, testnet environment secret is used.
I guess you need to remove this to change this github actions from deployment to check.

2023-03-24 08:43 UTC, YasunoriMATSUOKA approved these changes
![LGTM](https://image.lgtmoon.dev/184442)

2023-03-24 08:43 UTC, merged